export const kanbanGrid = [
    { headerText: 'To Do',
      keyField: 'Open',
      allowToggle: false },
  
    { headerText: 'In Progress',
      keyField: 'InProgress',
      allowToggle: false },
  
    { headerText: 'Testing',
      keyField: 'Testing',
      allowToggle: false,
      isExpanded: false },
  
    { headerText: 'Done',
      keyField: 'Close',
      allowToggle: false },
  ];

  export const kanbanData = [
    {
      Id: 'Task 1',
      Title: 'Adding the feedback section',
      Status: 'Open',
      Summary: 'Analyze the reviews gathered from the customer.',
      Type: 'Story',
      Priority: 'Low',
      Tags: 'Feedback',
      Estimate: 3.5,
      Project: 'Film Fiesta',
      RankId: 1,
      Color: '#02597B',
      ClassName: 'e-story, e-low, e-nancy-davloio',
    },
    {
      Id: 'Task 2',
      Title: 'Fixing server Bugs',
      Status: 'InProgress',
      Summary: 'Improve application performance',
      Type: 'Improvement',
      Priority: 'Normal',
      Tags: 'Improvement',
      Estimate: 6,
      Project: 'Film Fiesta',
      RankId: 1,
      Color: '#683A68',
      ClassName: 'e-improvement, e-normal, e-andrew-fuller',
    },
    {
      Id: 'Task 3',
      Title: 'Integrating Chat Features',
      Status: 'InProgress',
      Summary: 'Adding the Chat Features with the team-mates',
      Type: 'Others',
      Priority: 'Critical',
      Tags: 'Meeting',
      Estimate: 5.5,
      Project: 'Simplex',
      RankId: 2,
      Color: '#1F88E5',
      ClassName: 'e-others, e-critical, e-janet-leverling',
    },
    {
      Id: 'Task 4',
      Title: 'Browser Issues',
      Status: 'InProgress',
      Summary: 'Fix the issues reported in the IE browser.',
      Type: 'Bug',
      Priority: 'Critical',
      Tags: 'IE, Issues',
      Estimate: 2.5,
      Project: 'Git Prodigy',
      RankId: 2,
      Color: '#E64A19',
      ClassName: 'e-bug, e-release, e-janet-leverling',
    },
    {
      Id: 'Task 5',
      Title: 'Bug Fixing',
      Status: 'Testing',
      Summary: 'Fix the issues reported by the customer.',
      Type: 'Bug',
      Priority: 'Low',
      Tags: 'Customer',
      Estimate: '3.5',
      Project: 'Simplex',
      RankId: 1,
      Color: '#E64A19',
      ClassName: 'e-bug, e-low, e-steven-walker',
    },

    {
        Id: 'Task 6',
        Title: 'Server bug Fixes',
        Status: 'Testing',
        Summary: 'Fix the issues reported by the customer.',
        Type: 'Bug',
        Priority: 'Critical',
        Tags: 'Customer Bugs',
        Estimate: '3.5',
        Project: 'Pixel Craft',
        RankId: 1,
        Color: '#E64A19',
        ClassName: 'e-bug, e-critical, e-steven-walker',
      },
    {
      Id: 'Task 7',
      Title: 'Browser Bug',
      Status: 'Review',
      Summary: 'Fix the issues reported in Safari browser.',
      Type: 'Bug',
      Priority: 'Critical',
      Tags: 'Fix,Safari,Bug',
      Estimate: 1.5,
      Project: 'StreamFlow',
      RankId: 2,
      Color: '#E64A19',
      ClassName: 'e-bug, e-release, e-nancy-davloio',
    },
    {
      Id: 'Task 8',
      Title: 'Testing Application',
      Status: 'Close',
      Summary: 'Test the application in the IE browser.',
      Type: 'Story',
      Priority: 'Low',
      Tags: 'Review,IE',
      Estimate: 5.5,
      Project: 'ByteWave',
      RankId: 3,
      Color: '#02897B',
      ClassName: 'e-story, e-low, e-margaret-hamilt',
    },
    {
      Id: 'Task 9',
      Title: 'Validation',
      Status: 'Validate',
      Summary: 'Validate the issues reported by the customer.',
      Type: 'Story',
      Priority: 'High',
      Tags: 'Validation,Fix',
      Estimate: 1,
      Project: 'Pixel Craft',
      RankId: 1,
      Color: '#02897B',
      ClassName: 'e-story, e-high, e-steven-walker',
    },
    
   
  ];